name: Build and Deploy

on:
  push:
    branches:
      - back/cooperear-clean
      - main
  pull_request:
    branches:
      - back/cooperear-clean
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: rookies-3/rookies-oneteam

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List directory structure
      run: |
        echo "=== Root directory ==="
        ls -la
        echo "=== rookies-oneteam directory ==="
        ls -la rookies-oneteam/ || echo "No rookies-oneteam directory found"
        find . -name "Dockerfile" -type f
        find . -name "build.gradle" -type f
        find . -name "gradlew" -type f
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x rookies-oneteam/gradlew
    
    - name: Build with Gradle
      run: |
        cd rookies-oneteam
        ./gradlew clean build
    
    - name: List build outputs
      run: |
        cd rookies-oneteam
        ls -lh build/libs/
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: rookies-oneteam-jar
        path: rookies-oneteam/build/libs/*.jar
        retention-days: 7
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
    
    - name: Verify files before Docker build
      run: |
        echo "Dockerfile location:"
        ls -la rookies-oneteam/Dockerfile
        echo "JAR files location:"
        ls -lh rookies-oneteam/build/libs/*.jar
        echo "Build context:"
        pwd
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: rookies-oneteam
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

